### PR TITLE
Update ankiweb.html

### PR DESCRIPTION
**Pull request by guillemps**
I just used you add-on for styling relearning cards and found out they were not documented. Thank you for sharing this add-on !

### CODE REVIEW

**Comment by ijgnd** [comment]
Thanks for spotting my omission.

I think "relearning" is not the best wording. But the scheduler is complicated so I prefer to check multiple times: 

The popular database description at https://github.com/ankidroid/Anki-Android/wiki/Database-Structure has this:

    3=in learning, next rev in at least a day after the previous review

The official description seems to be "day lrn", see [here](https://github.com/ankitects/anki/blob/e3a57a41936d57314cb72996955aaaf45f313c9c/pylib/anki/sched.py#L20) and now the scheduler now refers to it as QUEUE_TYPE_DAY_LEARN_RELEARN. But that's not clear at all. 

this [part](https://github.com/ankitects/anki/blob/e3a57a41936d57314cb72996955aaaf45f313c9c/pylib/anki/sched.py#L639) of the source code is also useful. 

Maybe "(Re)Learning - next day or later"?

**Comment by guillemps** [comment]
Sure. At my understanding, 3 stands for learning or relearning card which has at least one graduation step above 1440 minutes. By the way I noticed 'day learning' on {{info-Type:}}.

**Comment by ijgnd** [comment]
First of all: Thanks for notifying me about another mistake in my description.

I continued to look into the scheduler tonight and I learned something new. For the difference between type and queue and I found this [post from the anki developer](https://github.com/ankitects/anki/pull/433#discussion_r373816291) from February 2020:

> type and queue are related, but not interchangeable. For example, type=3 means a relearning card, but queue=3 means a learning or relearning card with a 24+ hour interval.

So maybe we should have something like this?

    {{info-Type:}} - 0=suspended, 1=learning, 2=review, 3=relearn

**Comment by guillemps** [comment]
Interesting. I was not fully aware of the diference between queue and type.

**Pull request merged**
